##############################################################################
# GitHub Actions Workflow to test building PolyFit with GCC
#
# Copyright (C) 2022 Liangliang Nan <liangliang.nan@gmail.com>
#
# Licensed under GNU LGPL.3, see LICENCE file
##############################################################################
name: test-build-gcc

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.compilers }}
    strategy:
          fail-fast: false
          matrix:
            compilers: [g++-7, g++-8, g++-9, g++-10, g++-11]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - run: sudo apt-get update || true;
             sudo apt-get install ${{ matrix.compilers }};
             sudo apt-get install build-essential libglu1-mesa-dev freeglut3-dev mesa-common-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libboost-all-dev libcgal-dev qt5-default;
             rm -rf Release;
             mkdir Release;
             cd Release;
             cmake -DCMAKE_CXX_COMPILER=${{ matrix.compilers }} -DCMAKE_BUILD_TYPE=Release ..;
             make;
             
